#!python

#Thisprogram that displays the lyrics to “99 Bottles of Beer.” 
# Each stanza of the song goes like this:

# X bottles of beer on the wall,

# X bottles of beer,

# Take one down,

# Pass it around,

# X – 1 bottles of beer on the wall,

# The X in the song starts at 99 and decreases by one for each 
# stanza. When X is one (and X – 1 is zero), the last line is 
# “No more bottles of beer on the wall!” After each stanza, 
# display a blank line to separate it from the next stanza. 

X = 99

while X >= 2:
    print(f"{X} bottles of beer on the wall,\n"
          f"{X} bottles of beer,\n"
          "Take one down,\n"
          "Pass it around,\n"
          f"{X - 1} bottles of beer on the wall.\n")
    X = X - 1

if X == 1:
    print("1 bottle of beer on the wall,\n"
          "1 bottle of beer,\n"
          "Take one down,\n"
          "Pass it around,\n"
          "No more bottles of beer on the wall!\n")
    